// Team name normalization: map feed variants → canonical names
const TEAM_MAP = {
  'USA': 'United States',
  'United States': 'United States',
  'Korea Republic': 'South Korea',
  'South Korea': 'South Korea',
  'Türkiye': 'Türkiye',
  'Turkey': 'Türkiye',
  'Czechia': 'Czechia',
  'Czech Republic': 'Czechia',
  'Côte d\'Ivoire': 'Ivory Coast',
  'Ivory Coast': 'Ivory Coast',
  'Cote d\'Ivoire': 'Ivory Coast',
  'CIV': 'Ivory Coast',
  'Cabo Verde': 'Cape Verde',
  'Cape Verde': 'Cape Verde',
  'CPV': 'Cape Verde',
  'Congo DR': 'DR Congo',
  'DR Congo': 'DR Congo',
  'Democratic Republic of the Congo': 'DR Congo',
  'COD': 'DR Congo',
  'Bosnia and Herzegovina': 'Bosnia-Herzegovina',
  'Bosnia-Herzegovina': 'Bosnia-Herzegovina',
  'Curaçao': 'Curaçao',
  'Curacao': 'Curaçao',
  'CUW': 'Curaçao',
  'Mexico': 'Mexico',
  'South Africa': 'South Africa',
  'RSA': 'South Africa',
  'Brazil': 'Brazil',
  'Haiti': 'Haiti',
  'Morocco': 'Morocco',
  'Scotland': 'Scotland',
  'Australia': 'Australia',
  'Paraguay': 'Paraguay',
  'Ecuador': 'Ecuador',
  'Germany': 'Germany',
  'Germany': 'Germany',
  'Japan': 'Japan',
  'Netherlands': 'Netherlands',
  'Sweden': 'Sweden',
  'Tunisia': 'Tunisia',
  'Belgium': 'Belgium',
  'Egypt': 'Egypt',
  'Iran': 'Iran',
  'New Zealand': 'New Zealand',
  'Spain': 'Spain',
  'Uruguay': 'Uruguay',
  'Saudi Arabia': 'Saudi Arabia',
  'France': 'France',
  'Iraq': 'Iraq',
  'Norway': 'Norway',
  'Senegal': 'Senegal',
  'Portugal': 'Portugal',
  'Colombia': 'Colombia',
  'Uzbekistan': 'Uzbekistan',
  'England': 'England',
  'Ghana': 'Ghana',
  'Croatia': 'Croatia',
  'Panama': 'Panama',
  'Argentina': 'Argentina',
  'Austria': 'Austria',
  'Algeria': 'Algeria',
  'Jordan': 'Jordan',
  'Qatar': 'Qatar',
  'Switzerland': 'Switzerland',
  'Canada': 'Canada',
  'Belgium': 'Belgium',
  'Iran': 'Iran'
};

function normalize(teamName) {
  if (!teamName) return null;
  const canonical = TEAM_MAP[teamName];
  if (!canonical) throw new Error(`Unmapped team: "${teamName}". Add to TEAM_MAP.`);
  return canonical;
}

module.exports = { normalize, TEAM_MAP };
