// Team name normalization: map feed variants → canonical names
const TEAM_MAP = {
  'USA': 'United States',
  'United States': 'United States',
  'Korea Republic': 'South Korea',
  'South Korea': 'South Korea',
  'Südkorea': 'South Korea',
  'Türkiye': 'Türkiye',
  'Turkey': 'Türkiye',
  'Tschechien': 'Czechia',
  'Czechia': 'Czechia',
  'Czech Republic': 'Czechia',
  'Côte d\'Ivoire': 'Ivory Coast',
  'Ivory Coast': 'Ivory Coast',
  'Elfenbeinküste': 'Ivory Coast',
  'Cote d\'Ivoire': 'Ivory Coast',
  'CIV': 'Ivory Coast',
  'Cabo Verde': 'Cape Verde',
  'Kap Verde': 'Cape Verde',
  'Cape Verde': 'Cape Verde',
  'CPV': 'Cape Verde',
  'Kongo DR': 'DR Congo',
  'DR Kongo': 'DR Congo',
  'Congo DR': 'DR Congo',
  'DR Congo': 'DR Congo',
  'Democratic Republic of the Congo': 'DR Congo',
  'COD': 'DR Congo',
  'Bosnien und Herzegowina': 'Bosnia-Herzegovina',
  'Bosnia and Herzegovina': 'Bosnia-Herzegovina',
  'Bosnia-Herzegovina': 'Bosnia-Herzegovina',
  'Curaçao': 'Curaçao',
  'Curacao': 'Curaçao',
  'CUW': 'Curaçao',
  'Mexiko': 'Mexico',
  'Mexico': 'Mexico',
  'Südafrika': 'South Africa',
  'South Africa': 'South Africa',
  'RSA': 'South Africa',
  'Brasilien': 'Brazil',
  'Brazil': 'Brazil',
  'Haiti': 'Haiti',
  'Marokko': 'Morocco',
  'Morocco': 'Morocco',
  'Schottland': 'Scotland',
  'Scotland': 'Scotland',
  'Australien': 'Australia',
  'Australia': 'Australia',
  'Paraguay': 'Paraguay',
  'Ecuador': 'Ecuador',
  'Deutschland': 'Germany',
  'Türkei': 'Türkiye',
  'Germany': 'Germany',
  'Japan': 'Japan',
  'Niederlande': 'Netherlands',
  'Netherlands': 'Netherlands',
  'Schweden': 'Sweden',
  'Sweden': 'Sweden',
  'Tunesien': 'Tunisia',
  'Tunisia': 'Tunisia',
  'Belgien': 'Belgium',
  'Belgium': 'Belgium',
  'Ägypten': 'Egypt',
  'Egypt': 'Egypt',
  'Iran': 'Iran',
  'Irak': 'Iraq',
  'Iraq': 'Iraq',
  'New Zealand': 'New Zealand',
  'Neuseeland': 'New Zealand',
  'Spanien': 'Spain',
  'Spain': 'Spain',
  'Uruguay': 'Uruguay',
  'Saudi Arabien': 'Saudi Arabia',
  'Saudi Arabia': 'Saudi Arabia',
  'Frankreich': 'France',
  'France': 'France',
  'Iraq': 'Iraq',
  'Norwegen': 'Norway',
  'Norway': 'Norway',
  'Senegal': 'Senegal',
  'Portugal': 'Portugal',
  'Colombia': 'Colombia',
  'Kolumbien': 'Colombia',
  'Usbekistan': 'Uzbekistan',
  'Uzbekistan': 'Uzbekistan',
  'England': 'England',
  'Ghana': 'Ghana',
  'Kroatien': 'Croatia',
  'Croatia': 'Croatia',
  'Panama': 'Panama',
  'Argentinien': 'Argentina',
  'Argentina': 'Argentina',
  'Österreich': 'Austria',
  'Austria': 'Austria',
  'Algerien': 'Algeria',
  'Algeria': 'Algeria',
  'Jordanien': 'Jordan',
  'Jordan': 'Jordan',
  'Katar': 'Qatar',
  'Qatar': 'Qatar',
  'Schweiz': 'Switzerland',
  'Switzerland': 'Switzerland',
  'Kanada': 'Canada',
  'Canada': 'Canada'
};

function normalize(teamName) {
  if (!teamName) return null;
  const canonical = TEAM_MAP[teamName.trim()];
  if (!canonical) {
    // Fail-safe: never throw. A single unmapped name must NOT break the whole
    // feed. Pass the raw name through — if it's genuinely unknown it simply
    // won't match a fixture (harmless skip), and the warning tells us to add it.
    console.warn(`[normalize] Unmapped team: "${teamName}" — passing through raw. Add it to TEAM_MAP if it should match a fixture.`);
    return teamName.trim();
  }
  return canonical;
}

module.exports = { normalize, TEAM_MAP };
